import {
  DollarSign,
  Users,
  Package,
  ShoppingCart,
  BarChart3,
  CreditCard,
  UtensilsCrossed,
  Hotel,
  Home,
  HardHat,
  Zap,
  Truck,
  ListChecks,
  Stethoscope,
  GraduationCap,
  ShieldCheck,
  Briefcase,
  Stamp,
  type LucideIcon,
} from "lucide-react";

export interface ModuleTile {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  color: string;
  bg: string;
  features: string[];
  href: string;
}

export const coreModules: ModuleTile[] = [
  {
    id: "finance",
    name: "Finance & Accounting",
    description: "Complete financial management with GL, AP/AR, bank reconciliation, multi-currency, and advanced financial reporting.",
    icon: DollarSign,
    color: "from-blue-500 to-indigo-600",
    bg: "bg-blue-500/10",
    features: ["General Ledger", "Accounts Payable/Receivable", "Bank Reconciliation", "Financial Reporting"],
    href: "/features#finance",
  },
  {
    id: "hr",
    name: "HR & Payroll",
    description: "End-to-end human resource management including payroll, leave, attendance, and performance management.",
    icon: Users,
    color: "from-purple-500 to-pink-600",
    bg: "bg-purple-500/10",
    features: ["Employee Management", "Payroll Processing", "Leave & Attendance", "Performance Reviews"],
    href: "/features#hr",
  },
  {
    id: "inventory",
    name: "Inventory & Procurement",
    description: "Full inventory control with warehouse management, stock tracking, procurement workflows, and vendor management.",
    icon: Package,
    color: "from-emerald-500 to-teal-600",
    bg: "bg-emerald-500/10",
    features: ["Stock Management", "Warehouse Control", "Procurement Workflow", "Vendor Management"],
    href: "/features#inventory",
  },
  {
    id: "sales",
    name: "Sales Management",
    description: "From quotation to invoice, manage the entire sales cycle with customer management and sales analytics.",
    icon: ShoppingCart,
    color: "from-orange-500 to-amber-600",
    bg: "bg-orange-500/10",
    features: ["Quotations & Orders", "Invoicing", "Customer Management", "Sales Analytics"],
    href: "/features#sales",
  },
  {
    id: "crm",
    name: "CRM",
    description: "Manage leads, opportunities, and pipeline with customer communication and activity tracking.",
    icon: Zap,
    color: "from-lime-500 to-green-600",
    bg: "bg-lime-500/10",
    features: ["Lead Management", "Pipeline View", "Opportunity Tracking", "Customer Comms"],
    href: "/features#crm",
  },
  {
    id: "purchase",
    name: "Purchase Management",
    description: "Streamline purchasing with RFQ management, purchase orders, vendor evaluation, and cost control.",
    icon: Truck,
    color: "from-slate-500 to-gray-600",
    bg: "bg-slate-500/10",
    features: ["RFQ Management", "Purchase Orders", "Vendor Evaluation", "Cost Control"],
    href: "/features#purchase",
  },
  {
    id: "project-management",
    name: "Project Management",
    description: "Plan, assign, and track projects and tasks with timelines, budgets, and team workloads in one place.",
    icon: ListChecks,
    color: "from-teal-500 to-cyan-600",
    bg: "bg-teal-500/10",
    features: ["Task & Milestone Tracking", "Timelines", "Budget Tracking", "Team Workload"],
    href: "/features#project-management",
  },
  {
    id: "analytics",
    name: "Reports",
    description: "Executive dashboards, business intelligence reports, and real-time KPI monitoring across all modules.",
    icon: BarChart3,
    color: "from-brand-500 to-indigo-600",
    bg: "bg-brand-500/10",
    features: ["Executive Dashboards", "BI Reports", "KPI Monitoring", "Custom Reports"],
    href: "/features#analytics",
  },
];

export const industryModules: ModuleTile[] = [
  {
    id: "pos",
    name: "Point of Sale",
    description: "Modern retail POS with barcode support, multi-store operations, and real-time inventory sync.",
    icon: CreditCard,
    color: "from-pink-500 to-rose-600",
    bg: "bg-pink-500/10",
    features: ["Retail POS", "Barcode Support", "Multi-store", "Real-time Sync"],
    href: "/features#pos",
  },
  {
    id: "restaurant",
    name: "Restaurant POS & KDS",
    description: "Complete restaurant management with table ordering, KDS integration, recipe management, and billing.",
    icon: UtensilsCrossed,
    color: "from-red-500 to-orange-600",
    bg: "bg-red-500/10",
    features: ["Table Management", "KDS Integration", "Recipe & Food Cost", "Waiter Ordering"],
    href: "/features#restaurant",
  },
  {
    id: "hospitality",
    name: "Hospitality Management",
    description: "Hotel management system with reservations, room management, guest services, and integrated billing.",
    icon: Hotel,
    color: "from-cyan-500 to-blue-600",
    bg: "bg-cyan-500/10",
    features: ["Reservations", "Room Management", "Guest Services", "Integrated Billing"],
    href: "/features#hospitality",
  },
  {
    id: "realestate",
    name: "Real Estate Management",
    description: "Manage properties, leasing, contracts, maintenance, and financial reporting for real estate portfolios.",
    icon: Home,
    color: "from-violet-500 to-purple-600",
    bg: "bg-violet-500/10",
    features: ["Property Management", "Leasing & Contracts", "Maintenance", "Financial Reports"],
    href: "/features#realestate",
  },
  {
    id: "construction",
    name: "Construction Management",
    description: "Project planning, resource allocation, cost tracking, and BOQ management for construction companies.",
    icon: HardHat,
    color: "from-yellow-500 to-amber-600",
    bg: "bg-yellow-500/10",
    features: ["Project Planning", "Resource Allocation", "Cost Tracking", "BOQ Management"],
    href: "/features#construction",
  },
  {
    id: "healthcare",
    name: "Healthcare",
    description: "Patient records, appointment scheduling, and integrated billing built for clinics and healthcare providers.",
    icon: Stethoscope,
    color: "from-rose-500 to-pink-600",
    bg: "bg-rose-500/10",
    features: ["Patient Records", "Appointment Scheduling", "Clinical Billing", "Compliance"],
    href: "/features#healthcare",
  },
  {
    id: "education",
    name: "Education",
    description: "Student records, admissions, and fee management for schools, colleges, and training institutes.",
    icon: GraduationCap,
    color: "from-indigo-500 to-blue-600",
    bg: "bg-indigo-500/10",
    features: ["Student Records", "Admissions", "Fee Management", "Academic Reporting"],
    href: "/features#education",
  },
  {
    id: "insurance",
    name: "Insurance",
    description: "Policy administration and claims tracking built for insurance providers and brokers.",
    icon: ShieldCheck,
    color: "from-green-500 to-emerald-600",
    bg: "bg-green-500/10",
    features: ["Policy Administration", "Claims Tracking", "Renewals", "Compliance Reporting"],
    href: "/features#insurance",
  },
  {
    id: "b2b-services",
    name: "B2B & Professional Services",
    description: "Proposals, project-based billing, and service CRM for B2B and professional services firms.",
    icon: Briefcase,
    color: "from-amber-500 to-orange-600",
    bg: "bg-amber-500/10",
    features: ["Proposals & Quotes", "Project Billing", "Service CRM", "Time & Expense"],
    href: "/features#b2b-services",
  },
  {
    id: "visa-services",
    name: "Visa Services",
    description: "Case management, document checklists, government submission tracking, and renewals for visa and immigration services.",
    icon: Stamp,
    color: "from-fuchsia-500 to-purple-600",
    bg: "bg-fuchsia-500/10",
    features: ["Case Management", "Document Checklists", "Submission Tracking", "Renewals"],
    href: "/features#visa-services",
  },
];

export const totalModuleCount = coreModules.length + industryModules.length;
